name: container_and_sizedbox
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: any
  animated_text_kit: ^4.2.2
  image_picker: ^1.1.2
  geolocator: ^11.0.0
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.2
  firebase_auth: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
 
